name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Install dependencies
        run: uv sync --group dev --group tests

      - name: Ruff
        run: uv run ruff check .

      - name: Mypy
        run: uv run mypy aiointercept

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        aiohttp-version: ["3.13.3", "3.14.0"]
        include:
          - os: windows-latest
            python-version: "3.14"
            aiohttp-version: "3.14.0"
          - os: macos-latest
            python-version: "3.14"
            aiohttp-version: "3.14.0"
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Install dependencies
        run: uv sync --group tests

      - name: Pin aiohttp version
        run: uv pip install aiohttp==${{ matrix.aiohttp-version }}

      - name: Tests
        run: |
          uv run coverage run -m pytest tests/
          uv run coverage report --fail-under=99
